[font]
size = 13.0

[font.normal]
family = "Fira Code"

[scrolling]
history = 0
multiplier = 0

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t="

[window]
dynamic_padding = true

[window.padding]
x = 5
y = 5

[[hints.enabled]]
regex = "(https:|http:|file:|git:|ssh:) [^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"

action = "Copy"
post_processing = true
mouse.enabled = true
mouse.mods = "None"
