font:
  size: 16.0
scrolling:
  history: 0
  multiplier: 0
selection:
  save_to_clipboard: true
colors:
  primary:
    background: '#1c1c1c'
window:
  padding:
    x: 5
    y: 5
  dynamic_padding: true
