setopt prompt_subst
export WORDCHARS='*?[]~=&;!#$%^(){}'

# Set up path

# Pip installations
export PATH=$HOME/.local/bin:/root/.local/bin:$PATH
# Cargo installation
# TODO might not need the export due to the line that follows it
export PATH=$HOME/.cargo/bin:$PATH
. "$HOME/.cargo/env"

# History settings

setopt hist_ignore_dups
HISTFILE=~/.zsh_history
HISTSIZE=1000000
SAVEHIST=1000000
setopt extendedglob notify
setopt append_history
setopt inc_append_history
unsetopt autocd
bindkey -e

# Completions

autoload -Uz compinit
compinit
setopt complete_in_word
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'

# Auto escape carets

bindkey '^' self-insert-backslash
function self-insert-backslash() { LBUFFER+='\'; zle .self-insert }
zle -N self-insert-backslash

# Some helpers that are bound to aliases

tmux_name_window_after_directory() {
  tmux rename-window -t${TMUX_PANE} `basename $PWD`
}

tmux_name_window() {
  tmux rename-window -t${TMUX_PANE} `basename $1`
}

grep_history() {
  cat ~/.zsh_history | grep $1
}
