# Load aliases
if [ -e "$HOME/.aliases" ]; then
  source "$HOME/.aliases"
fi

# Load private environment variables
if [ -e "$HOME/.private_environment" ]; then
  source "$HOME/.private_environment"
fi

# Ignore duplicate history entries
setopt histignoredups

# Allow comments in shell
setopt interactivecomments

# Automatically change into directories without `cd`
setopt auto_cd

# automatically pushd
setopt auto_pushd
export dirstacksize=5

# Enable extended globbing
setopt EXTENDED_GLOB

# Use nvim as an editor
export EDITOR='nvim'
export VISUAL='nvim'

# Prompt helpers

git_prompt() {
  BRANCH=$(git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/*\(.*\)/\1/')

  if [ ! -z $BRANCH ]; then
    STATUS=$(git rev-parse --short HEAD)
    echo "%F{238}$BRANCH@${STATUS}"
  fi
}

function set-prompt() {
  emulate -L zsh
  PROMPT="%F{238}%~$(git_prompt)"$'\n'"%F{240}%B∴%b %F{reset}"
}

# Set prompt using helpers

autoload -Uz add-zsh-hook
add-zsh-hook precmd set-prompt
setopt noprompt{bang,subst} prompt{cr,percent,sp}

# Configure lab completions
source <(lab completion zsh)

# Load zsh completions installed by apps
fpath+=/home/mike/.zsh_functions

# Configure NVM
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
