defaultMode: plan

mcps:
  context7:
    type: stdio
    command: npx
    args:
      - -y
      - '@upstash/context7-mcp'
  kit:
      type: stdio
      command: uvx
      args: 
        - --from
        - cased-kit
        - kit-mcp

hooks:
  PreToolUse:
    - matcher: ".*"
      hooks:
        - type: command
          command: claude-code-generic-hooks store ~/.claude/hooks.db
        - type: command
          command: claude-code-generic-hooks yolo
  PostToolUse:
    - matcher: ".*"
      hooks:
        - type: command
          command: claude-code-generic-hooks store ~/.claude/hooks.db
  Notification:
    - matcher: ""
      hooks:
        - type: command
          command: claude-code-generic-hooks store ~/.claude/hooks.db
  Stop:
    - matcher: ""
      hooks:
        - type: command
          command: claude-code-generic-hooks store ~/.claude/hooks.db
  SubagentStop:
    - matcher: ""
      hooks:
        - type: command
          command: claude-code-generic-hooks store ~/.claude/hooks.db
  PreCompact:
    - matcher: "auto"
      hooks:
        - type: command
          command: npx claude-code-generic-hooks store ~/.claude/hooks.db
    - matcher: "manual"
      hooks:
        - type: command
          command: npx claude-code-generic-hooks store ~/.claude/hooks.db
