#!/usr/bin/env bash

hc() {
    herbstclient "$@"
}

hc emit_hook reload

xsetroot -solid 'black'

hc keyunbind --all
Mod=Mod4
Alt=Mod1

hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-c close

default_term='alacritty'
hc keybind $Mod-Return spawn ${TERMINAL:-$default_term}

hc keybind $Mod-d spawn rofi -show run
hc keybind $Mod-b spawn qutebrowser

hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

hc keybind $Mod-u       split   bottom  0.5
hc keybind $Mod-o       split   right   0.5
hc keybind $Mod-Control-space split explode

resize_step=0.01
hc keybind $Mod-Control-h       resize left +$resize_step
hc keybind $Mod-Control-j       resize down +$resize_step
hc keybind $Mod-Control-k       resize up +$resize_step
hc keybind $Mod-Control-l       resize right +$resize_step

hc set_attr settings.default_frame_layout horizontal
hc load '(clients horizontal:0)'

tag_names=( {1..9} )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}" ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

move_floated_step=30
hc keybind Control-Alt-h spawn hc_move_floated x-axis +$move_floated_step
hc keybind Control-Alt-j spawn hc_move_floated y-axis -$move_floated_step
hc keybind Control-Alt-k spawn hc_move_floated y-axis +$move_floated_step
hc keybind Control-Alt-l spawn hc_move_floated x-axis -$move_floated_step

resize_floated_step=30
hc keybind Control-Alt-Shift-h spawn hc_resize_floated x-axis +$resize_floated_step
hc keybind Control-Alt-Shift-j spawn hc_resize_floated y-axis -$resize_floated_step
hc keybind Control-Alt-Shift-k spawn hc_resize_floated y-axis +$resize_floated_step
hc keybind Control-Alt-Shift-l spawn hc_resize_floated x-axis -$resize_floated_step

hc keybind $Mod-r remove
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-Shift-f set_attr clients.focus.floating toggle

# Cycle all layouts
hc keybind $Mod-Shift-space \
            or , and . compare tags.focus.curframe_wcount = 2 \
                     . cycle_layout +1 vertical horizontal max vertical grid \
               , cycle_layout +1
# Cycle horizontal and maximized
hc keybind $Mod-space \
            or , and . compare tags.focus.curframe_wcount = 2 \
                     . cycle_layout +1 horizontal max \
               , cycle_layout +1

hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent

# Cycle clients
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
# Eventually get rid of this some way and use the above binding
hc keybind $Alt-Tab         cycle_all +1
hc keybind $Alt-Shift-Tab   cycle_all -1

# Constrain fullscreen inside frame
hc keybind $Mod-Control-f chain \
  , attr clients.focus.ewmhrequests off \
  , attr clients.focus.ewmhnotify on \
  , attr clients.focus.fullscreen on \
  , attr clients.focus.ewmhnotify off \
  , set_attr clients.focus.fullscreen off \
  , set_attr clients.focus.ewmhnotify on \
  , sprintf CMD 'sleep 2 ; herbstclient attr clients.%s.ewmhrequests on' clients.focus.winid spawn bash -c CMD

hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color 'black'
hc set frame_border_normal_color 'black'
hc set frame_bg_normal_color '#1c1c1c'
hc set frame_bg_active_color '#585858'
hc set frame_border_width 1
hc set always_show_frame on
hc set frame_bg_transparent on
hc set frame_transparent_width 5
hc set frame_gap 2

hc attr theme.title_height 0
hc attr theme.active.color 'black'
hc attr theme.title_color 'white'
hc attr theme.normal.color 'black'
hc attr theme.urgent.color '#af005f'
hc attr theme.normal.title_color '#898989'
hc attr theme.inner_width 2
hc attr theme.inner_color black
hc attr theme.border_width 5
hc attr theme.floating.border_width 4
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color black
hc attr theme.active.inner_color '#585858'
hc attr theme.urgent.inner_color '#1c1c1c'
hc attr theme.normal.inner_color '#1c1c1c'
hc attr theme.active.outer_color 'black'
hc attr theme.urgent.outer_color 'black'
hc attr theme.normal.outer_color 'black'
hc attr theme.active.outer_width 1
hc attr theme.background_color '#141414'

hc set window_gap 0
hc set frame_padding 0
hc set smart_window_surroundings off
hc set smart_frame_surroundings on
hc set mouse_recenter_gap 0

hc unrule -F
hc rule focus=on
hc rule floatplacement=smart
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

hc set tree_style '╾│ ├└╼─┐'

hc unlock
